<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= esc($title) ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
    <style>body{background:#f3f6fb}.navbar{background:#102a56}.brand{color:#fff;font-weight:800}.card,.panel{border:0;border-radius:18px;box-shadow:0 8px 30px #102a5612}.stat{color:#fff;border-radius:16px;padding:1.1rem}.stat h2{margin:0;font-weight:800}.stat-total{background:#1e40af}.stat-active{background:#16805b}.stat-inactive{background:#b45309}.stat-suspended{background:#be123c}.table thead th{white-space:nowrap}.pager-bar{display:flex;justify-content:space-between;align-items:center;gap:1rem;border-top:1px solid #e9edf3;padding-top:1rem}.pager-button{display:inline-flex;align-items:center;gap:.35rem;border:1px solid #d7deea;border-radius:9px;padding:.5rem .85rem;text-decoration:none;color:#1e40af;background:#fff;font-weight:600}.pager-button:hover{background:#eef4ff}.pager-button.disabled{color:#9aa5b5;background:#f7f8fa;pointer-events:none}.pager-status{color:#657189;font-size:.9rem}</style>
</head>
<body>
<nav class="navbar navbar-dark"><div class="container"><a class="navbar-brand brand" href="<?= base_url('dashboard') ?>">⚡ Puihaha Electric</a><div class="d-flex align-items-center gap-3 text-white"><span class="d-none d-md-inline">Welcome, <?= esc(session()->get('user_name')) ?></span><a class="btn btn-outline-light btn-sm" href="<?= base_url() ?>">Website</a><a class="btn btn-warning btn-sm" href="<?= base_url('logout') ?>">Log out</a></div></div></nav>
<main class="container py-4">
<?php if ($message = session()->getFlashdata('success')): ?><div class="alert alert-success alert-dismissible fade show"><?= esc($message) ?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>
<?php if ($message = session()->getFlashdata('error')): ?><div class="alert alert-danger alert-dismissible fade show"><?= esc($message) ?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><div class="text-primary">Puihaha Electric Company</div><h1 class="h3 mb-0">Customer account dashboard</h1></div><a href="<?= base_url('accounts/new') ?>" class="btn btn-primary"><i class="bi bi-plus-lg"></i> New account</a></div>
<div class="row g-3 mb-4"><div class="col-6 col-lg-3"><div class="stat stat-total"><h2><?= $total_accounts ?></h2><div>Total accounts</div></div></div><div class="col-6 col-lg-3"><div class="stat stat-active"><h2><?= $active_accounts ?></h2><div>Active</div></div></div><div class="col-6 col-lg-3"><div class="stat stat-inactive"><h2><?= $inactive_accounts ?></h2><div>Inactive</div></div></div><div class="col-6 col-lg-3"><div class="stat stat-suspended"><h2><?= $suspended_accounts ?></h2><div>Suspended</div></div></div></div>
<div class="panel bg-white p-3 p-md-4"><form class="row g-2 mb-4" method="get" action="<?= base_url('dashboard') ?>"><div class="col-md-5"><input class="form-control" name="search" value="<?= esc($search_keyword ?? '') ?>" placeholder="Search name, account, email, phone"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All statuses</option><?php foreach (['active','inactive','suspended'] as $option): ?><option value="<?= $option ?>" <?= $filter_status === $option ? 'selected' : '' ?>><?= ucfirst($option) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><select class="form-select" name="type"><option value="">All types</option><?php foreach (['residential','commercial','industrial'] as $option): ?><option value="<?= $option ?>" <?= $filter_type === $option ? 'selected' : '' ?>><?= ucfirst($option) ?></option><?php endforeach; ?></select></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-primary flex-grow-1" type="submit"><i class="bi bi-search"></i></button><a class="btn btn-light" href="<?= base_url('dashboard') ?>" title="Clear filters"><i class="bi bi-x-lg"></i></a></div></form>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Account</th><th>Customer</th><th>Contact</th><th>Connection</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody><?php if (!$accounts): ?><tr><td colspan="6" class="text-center text-muted py-5">No customer accounts found.</td></tr><?php endif; ?><?php foreach ($accounts as $account): ?><tr><td><strong><?= esc($account['account_number']) ?></strong><div class="small text-muted">Meter: <?= esc($account['meter_number']) ?></div></td><td><?= esc($account['customer_name']) ?><div class="small text-muted"><?= esc($account['address']) ?></div></td><td><?= esc($account['email']) ?><div class="small text-muted"><?= esc($account['phone']) ?></div></td><td><span class="badge text-bg-info"><?= ucfirst(esc($account['connection_type'])) ?></span></td><td><span class="badge text-bg-<?= $account['status'] === 'active' ? 'success' : ($account['status'] === 'suspended' ? 'warning' : 'secondary') ?>"><?= ucfirst(esc($account['status'])) ?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?= base_url('accounts/edit/'.$account['id']) ?>"><i class="bi bi-pencil"></i> Edit</a> <form class="d-inline" method="post" action="<?= base_url('accounts/delete/'.$account['id']) ?>" onsubmit="return confirm('Delete this customer account?');"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger" type="submit"><i class="bi bi-trash"></i></button></form></td></tr><?php endforeach; ?></tbody></table></div>
<?php if ($pager && $pager->getPageCount() > 1): ?>
<?php $pager->only(['page', 'search', 'status', 'type']); ?>
<div class="pager-bar mt-3">
    <?php if ($pager->getCurrentPage() > 1): ?><a class="pager-button" href="<?= esc((string) $pager->getPreviousPageURI('default')) ?>">← Previous</a><?php else: ?><span class="pager-button disabled">← Previous</span><?php endif; ?>
    <span class="pager-status">Page <?= $pager->getCurrentPage() ?> of <?= $pager->getPageCount() ?></span>
    <?php if ($pager->getCurrentPage() < $pager->getPageCount()): ?><a class="pager-button" href="<?= esc((string) $pager->getNextPageURI('default')) ?>">Next →</a><?php else: ?><span class="pager-button disabled">Next →</span><?php endif; ?>
</div>
<?php endif; ?></div></main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script></body></html>
